### ISSUE TITLE
Logging of Prompt Requests and Responses with Model Metrics

### ISSUE THREAD

**Issue by houssam38** [echolabsdev/prism#60] opened 2024-11-12 08:02 UTC
Hi, 

Add a logging feature to capture prompt requests and responses, including details such as the model name, input token count, and output token count.

This feature would provide valuable metrics on model usage, helping track and analyze how each model is utilized. Having these metrics available could also aid in optimizing prompt inputs, monitoring token usage, and managing costs.

Thx

**Comment by sixlive** [comment] 2024-11-12 14:40
This data should be available.

```php
$response = Prism::text()
    ->using(Provider::Anthropic, 'claude-3-sonnet')
    ->withPrompt('Explain quantum computing.')
    ->generate();
```

Total token usage for the request/response:

```php
$response->usage->promptTokens
$response->usage->completionTokens
 ```
 
 If you are using multi-step generation then you can get the usage of each step:
 
 ```php
 foreach ($response->steps as $step) {
    echo "Prompt tokens: {$step->usage->promptTokens}";
    echo "Completion tokens: {$step->usage->completionTokens}";
}
 ```
 
 You can also see all the messages but inspecting each step. Each step is an instance of `TextResult`:

 ```php
 class TextResult
{
    /**
     * @param  array<int, ToolCall>  $toolCalls
     * @param  array<int, ToolResult>  $toolResults
     * @param  array{id: string, model: string}  $response
     * @param  array<int, Message>  $messages
     */
    public function __construct(
        public readonly string $text,
        public readonly FinishReason $finishReason,
        public readonly array $toolCalls,
        public readonly array $toolResults,
        public readonly Usage $usage,
        public readonly array $response,
        public readonly array $messages = [],
    ) {}
}
```

Was there something specific that you would like that we aren't returning?

**Comment by pushpak1300** [comment] 2024-11-13 16:12
sees duplicate of this https://github.com/echolabsdev/prism/issues/56

**Comment by sixlive** [comment] 2024-11-14 22:56
@houssam38 at the moment, I don't have plans to support storage mechanisms. 

@pushpak1300 I think #56 is more about exposing raw request/response data. As I understand it, this request is about adding storage of the parts of the request / response lifecycle.

**Closed by sixlive** 2024-11-14 22:56 UTC
